syntax = "proto3";

package holpaca;

service Stage {
  rpc Resize(ResizeRequest) returns (ResizeResponse) {}
  rpc GetStatus(GetStatusRequest) returns (GetStatusResponse) {}
}

service Controller {
  rpc Connect(ConnectRequest) returns (ConnectResponse) {}
  rpc Disconnect(DisconnectRequest) returns (DisconnectResponse) {}
}

message ResizeRequest {
  map<int32, PoolSize> poolSizes = 1;
}

message PoolSize {
  int64 deltaSize = 1;
  map<string, int64> externalDeltaSizes = 2;
}

message ResizeResponse {}

message GetStatusRequest {}

message GetStatusResponse {
  CacheStatus cacheStatus = 1;
}

message PoolStatus {
  int32 poolId = 1;
  uint64 maxSize = 2;
  uint64 usedSize = 3;
  uint32 diskIOPS = 4;
  uint32 evictions = 5;
  map<string, int64> externalSize = 6;
  map<int32, uint32> tailAccesses = 7;
  map<uint64, double> mrc = 8;
  bool active = 9;
  double qos = 10;
};

message CacheStatus {
  map<int32, PoolStatus> pools = 1;
  uint64 maxSize = 2;
}

message ConnectRequest {
  string cacheAddress = 1;
}

message ConnectResponse {}

message DisconnectRequest {
  string cacheAddress = 1;
}

message DisconnectResponse {}
