syntax = "proto3";

package holpaca;

service Stage {
  rpc Resize(ResizeRequest) returns (ResizeResponse) {}
  rpc ResizePool(ResizePoolRequest) returns (ResizePoolResponse) {}
  rpc GetCacheStatus(GetCacheStatusRequest) returns (GetCacheStatusResponse) {}
  rpc GetPoolStatus(GetPoolStatusRequest) returns (GetPoolStatusResponse) {}
}

message ResizeRequest {
  map<int32, int64> deltaSizes = 1;
}

message ResizeResponse {}

message ResizePoolRequest {
  int32 poolId = 1;
  int64 deltaSize = 2;
}

message ResizePoolResponse {}

message GetPoolStatusRequest {
  int32 poolId = 1;
}

message GetPoolStatusResponse {
  PoolStatus poolStatus = 1;
}

message GetCacheStatusRequest {}

message GetCacheStatusResponse {
  CacheStatus cacheStatus = 1;
}

message PoolStatus {
  int32 poolId = 1;
  uint64 maxSize = 2;
  uint64 usedSize = 3;
  map<int32, uint32> tailAccesses = 4;
  map<uint64, double> mrc = 5;
  uint32 diskIOPS = 6;
  uint32 lookups = 7;
  uint32 misses = 8;
  uint32 evictions = 9;
};

message CacheStatus {
  map<int32, PoolStatus> pools = 1;
  uint64 maxSize = 2;
}
